config/routes.rb
Rails.application.routes.draw do
  get 'report/run'

  root 'static_pages#home'
  
  get '/signup',  to: 'users#new'
  get '/send', to: 'application#send_simple_message'

  get '/report', to: 'static_pages#report'

  resources :stores
  resources :transactions
  resources :invoices
  resources :statuses
  resources :members
  resources :users

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:status)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.haml
= form_for(@status) do |f|
  - if @status.errors.any?
    #error_explanation
      %h2
        = pluralize(@status.errors.count, "error")
        prohibited this status from being saved:
      %ul
        - @status.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .actions
    = f.submit

app/views/statuses/edit.html.haml
%h1 Editing Status
= render 'form'
= link_to 'Show', @status
|
= link_to 'Back', statuses_path

app/views/statuses/index.html.haml
%p#notice= notice
%h1 Listing Statuses
%table.table
  %thead
    %tr
      %th Status
      %th{:colspan => "3"}
  %tbody
    - @statuses.each do |status|
      %tr
        %td= status.status
        %td= link_to 'Show', status
        %td= link_to 'Edit', edit_status_path(status)
        %td= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Status', new_status_path

app/views/statuses/new.html.haml
%h1 New Status
= render 'form'
= link_to 'Back', statuses_path

app/views/statuses/show.html.haml
%p#notice= notice
%p
  %strong Status:
  = @status.status
= link_to 'Edit', edit_status_path(@status)
|
= link_to 'Back', statuses_path