config/routes.rb
Rails.application.routes.draw do
  get 'report/run'

  root 'static_pages#home'
  
  get '/signup',  to: 'users#new'
  get '/send', to: 'application#send_simple_message'

  get '/report', to: 'static_pages#report'

  resources :stores
  resources :transactions
  resources :invoices
  resources :statuses
  resources :members
  resources :users

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
    belongs_to :store
    
    validates :store_id, presence: true
    validates :cost, presence: true
    
    def store_name
       self.store.name 
    end
    def store_phone
       self.store.phone 
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:store_id, :cost)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.haml
= form_for(@invoice) do |f|
  - if @invoice.errors.any?
    #error_explanation
      %h2
        = pluralize(@invoice.errors.count, "error")
        prohibited this invoice from being saved:
      %ul
        - @invoice.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :store_id
    %br/
    = f.number_field :store_id
  .field
    = f.label :cost
    %br/
    = f.number_field :cost
  .actions
    = f.submit

app/views/invoices/edit.html.haml
%h1 Editing Invoice
= render 'form'
= link_to 'Show', @invoice
|
= link_to 'Back', invoices_path

app/views/invoices/index.html.haml
%p#notice= notice
%h1 Listing Invoices
%table.table
  %thead
    %tr
      %th Store
      %th Phone
      %th Cost
      %th{:colspan => "3"}
  %tbody
    - @invoices.each do |invoice|
      %tr
        %td= invoice.store_name
        %td= invoice.store_phone
        %td= invoice.cost
        %td= link_to 'Show', invoice
        %td= link_to 'Edit', edit_invoice_path(invoice)
        %td= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Invoice', new_invoice_path

app/views/invoices/new.html.haml
%h1 New Invoice
= render 'form'
= link_to 'Back', invoices_path

app/views/invoices/show.html.haml
%p#notice= notice
%p
  %strong Store:
  = @invoice.store_name
%p
  %strong Cost:
  = @invoice.cost
= link_to 'Edit', edit_invoice_path(@invoice)
|
= link_to 'Back', invoices_path